### ISSUE TITLE
Call uselocale instead of setlocale

### ISSUE THREAD

**Issue by fweimer** [json-c/json-c#195]
`setlocale` is not thread-safe because it changes the default locale for all threads in the process. `uselocale` allows per-thread locale settings. (This concerns the function `json_tokener_parse_ex`.)

**Comment by hawicz** [comment]
If you have patches to merge, including the necessary autoconf changes to handle building on systems that don't include uselocale, I'd be happy to merge them.

**Comment by hawicz** [comment]
I took a stab at making these changes, and it's turning out to be more of a pain than expected.  One issue is that it appears that on some versions of Linux (at least Debian 8.4), uselocale(LC_NUMERIC, ...) doesn't actually work to change the decimal separator.
Adding an additional uselocale(LC_TIME, ...) works around the problem, but I have no idea why.

**Comment by hawicz** [comment]
It's definitely not broken in all versions of Linux, as CentOS 5.11 (yes, that's old, it's what I happen to have sitting around) works just fine.

**Comment by fweimer** [comment]
The patch is slightly inconsistent about which locale object is freed (`newloc` vs `duploc`). `newlocale` is special in the sense that it destroys its second argument.

What's more confusing is that there isn't a `uselocale` call for the constructed locale object.

**Comment by hawicz** [comment]
It turns out the parsing was completely broken, but that was being masked by the change from commit 51993c28 which introduced the use of json_object_new_double_s during parsing to store the original pre-parse string.  Even though, for example, "1.2" was being parsed as 1.0, because of the saved original string the json_object_to_json_string() calls in test_locale were re-emitting that instead of using the double value!  D'oh!
