### ISSUE TITLE
json-c/json.h not found 

### ISSUE THREAD

**Issue by peidong** [json-c/json-c#204]
Hello,

I write C code beginning with 
#include <json-c/json.h>

And compile with the command.
gcc test.c -ljson
Or
gcc test.c -ljson-c 

But the json.h is not found. 

P.S. I use both Intel Edison embedded Linux with json-c (0.11) installed and Mac osx with json-c (0.12) installed.

**Comment by hawicz** [comment]
There's not enough information here to know what the problem is.  I'd suggest checking whether json.h (and the other json-c headers) actually exist on your system, and if it's not installed into a normal location you might want to add an appropriate -I option to your compile line.
If you still nee help, please re-open this with more details.
