### ISSUE TITLE
There is no json_object_new_null()

### ISSUE THREAD

**Issue by ilyash** [json-c/json-c#226]
The only way I see to encode nulls is via `json_object_array_put_idx()` and it appears that nulls can not be encoded anywhere else (like `{"a": null}` for example). Please add support for encoding nulls uniformly, as any other type.

**Comment by ilyash** [comment]
Looking at the source code of `json_object_to_json_string_ext()` I've found that one can just pass NULL to get the effect. Just could find it in any examples on the net. I guess if there was a `json_object_new_null()` it would help discoverability.

**Comment by dota17** [comment]
> Issue #226 is basically asking to have the "null" type be treated the same as the other types, and implement it as an actual instance of a struct json_object, instead of a C NULL value.
There are many benefits to that consistency, but the problem with doing this is that it would be a major change to the API, as any existing code that was checking for null by comparing against NULL would no longer work the same.
The theoretically problematic json_type_null case isn't reachable since you can't actually allocate an object with type json_type_null (using the public API; json_object_new() is static).
The call to json_object_set_serializer() isn't actually valid to do on a NULL object (it'll abort at the assert in json_object_set_userdata()), which is just one example of what might be improved if we were to make null a first class json-c type.
The most we can do while maintaining API and ABI compatibility would be to, as @ilyash mentioned, create a json_object_new_null() "for visibility", but it would be just:

@hawicz As you said in PR  #428, for maintaining API and ABI compatibility, we had better to add a json_object_new_null() which just returns NULL. Or do nothing. I can submit this pr and close this issue. What's your opinion on this?

```
struct json_object *json_object_new_null()
{
    return NULL;
}
```

**Comment by ilyash-b** [comment]
> as any existing code that was checking for null by comparing against NULL would no longer work the same.

I understand the need for compatibility. I recommend not to perpetuate the problem - it will continue to cost to developers and many users of the library. New major version maybe?

> implement it as an actual instance of a struct json_object

Yes please! That's the right thing to do, we all know that, right? :P

**Comment by dota17** [comment]
json_object_new_null() has been added and this issue could be closed @hawicz
