### ISSUE TITLE
avoid double slashes from json

### ISSUE THREAD

**Issue by manafGadgeon** [json-c/json-c#228]
i tried to create a json with string contain slash.  like  this

`KA4IChkAGQAAAAAAAAAAAOAO4A4uDgAAAAAAAAoAGAAmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQD//wAAwf/A/8D/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA//8CAP7/BAD6/wgA9P8SAOb/JwA2/A39mP0AAAIA4P/wD939pf2w/eL87vxz/Nn7zasAAHMKAADIlAkKGAAYAAAAAAAAAAAA4Jbgls6UAAAAAAAACgAYACYAAAAAAAAAyf+9/7//vv/B/8D/wP+8/77/v//C/8D/vf+//8D/wP++/77/`

But i got result json with double slashes. one extra back slash
```

{ "result":
KA4IChkAGQAAAAAAAAAAAOAO4A4uDgAAAAAAAAoAGAAmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQD\/\/wAAwf\/A\/8D\/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA\/\/8CAP7\/BAD6\/wgA9P8SAOb\/JwA2\/A39mP0AAAIA4P\/wD939pf2w\/eL87vxz\/Nn7zasAAHMKAADIlAkKGAAYAAAAAAAAAAAA4Jbgls6UAAAAAAAACgAYACYAAAAAAAAAyf+9\/7\/\/vv\/B\/8D\/wP+8\/77\/"}
```
How it is? this is my code 

```
struct json_object *obj1;
obj1 = json_object_new_object();    
json_object_object_add(obj1, "result", json_object_new_string(data with slash));

```
How to resolve this?

**Comment by skizzerz** [comment]
Escaping forward slashes is valid JSON, so there's no harm in this beyond display/space reasons. Specify JSON_C_TO_STRING_NOSLASHESCAPE in your flags when calling json_object_to_string_ext() to turn it off, see also #201. That flag doesn't exist in 0.12, so you'll need to compile from source instead of grabbing a distro package.

**Comment by usergoodvery** [comment]
hi
is this flag destined to make it to the main release? If so when? Looking trough the tickets, the change was implemented in Nov 2015. It is a handy flag, otherwise because redacting that extra escape char from output is nuisance.

**Comment by usergoodvery** [comment]
for what it is worth I applied the patch (against the latest) manually because it is simple, but it doesn't seem t be working--in my environment at least

for this input: eG1eChJyw5d/I5 I get: eG1eChJyw5deG1eChJyw5d/I5
asically joined the two strings together, axing the part where / apears on left

Clearly, the code base has moved on since the patch was initially implemented. Has it move on enough to invalidate the patch?

**Comment by hawicz** [comment]
Yes, this will be in the next release.  Fwiw, the main thing holding that back is that I'd like to get some kind of selectable float output formatting included, but haven't had time to figure out a good way for that to work.

That repeated output you see sounds like a bug that got fixed at some other time.  There might be another simple patch that you can apply if you look through the history, but it's probably easier just to grab the most recent code.

**Comment by usergoodvery** [comment]
which one is the latest? the master branch?

**Comment by hawicz** [comment]
Yes
