### ISSUE TITLE
Adding an object to itself

### ISSUE THREAD

**Issue by usergoodvery** [json-c/json-c#260]
By mistake I did similar to below, which caused the my app to crash and gdb to spin out of control.
It is invalid of course, but not sure if there internal mechanism to detect/recover from that, at least not crash.

struct json_object *jobj=json_object_new_object();
json_object_object_add(jobj,"spin", jobj);

const char *jobj_str=json_object_to_json_string(jobj);

**Comment by hawicz** [comment]
That's one of the simplest cases of the general problem of loops in what should be a tree of objects.  Checking to prevent that on every add is likely to have some performance issues, but perhaps to_json_string could gain a depth limit.
Am I correct it crashed due to an excessively deep call stack?

**Comment by usergoodvery** [comment]
yes that is correct... bottomless stack

**Comment by hawicz** [comment]
Adding a check to json_object_to_json_string and having it fail after a few thousand levels of nesting is fairly easy, but doesn't fix other problematic operations, such as even just:

    struct json_object *jobj=json_object_new_object();
    json_object_object_add(jobj,"spin", jobj);
    json_object_object_add(jobj,"spin", some_other_obj);

which crashes because it ends up freeing jobj while trying to replace one of it's members.  Oops, and that's almost certainly just one of many places that would have a problem.

So, since it'll be difficult to cover all the cases within the code that would need to change to safely handle cycles, and since doing a true cycle check in json_object_object_add would be prohibitively expensive, I'm going to mostly punt and just add a quick fail-fast check in json_object_object_add when the object being modified and the one being added are the same.
Otherwise, creating a loop in the object tree should be considered programmer error, a misuse of the json-c API.
