### ISSUE TITLE
Resusing  json_tokener object

### ISSUE THREAD

**Issue by usergoodvery** [json-c/json-c#284]
Hi,
Is it it save to reuse json_tokener object across (non-concurrent, but successive) to json_tokener_parse_ex() or one must issue json_tokener_free() between each call to json_tokener_parse_ex()?

regards

**Comment by hawicz** [comment]
I you call json_tokener_reset() you can re-use the same json_tokener object.  That'll save you about 4 calls to free() over called json_tokener_free().

**Comment by usergoodvery** [comment]
That's great... is there an equivalent of that for json_object to avoid calling put/new

**Comment by hawicz** [comment]
No, and it doesn't make sense to have one for most object types since you can't change them.  For a json_type_object or json_type_array you can just remove all of its elements and remove it from its containing object (if any) to do roughly the equivalent of "reset".  However, if your goal is performance I suspect you'll find this to be of limited impact, especially for object trees of any size, and you efforts are probably best spent elsewhere.
