### ISSUE TITLE
json_tokener_parse_ex doesn't parse JSON values

### ISSUE THREAD

**Issue by yogo1212** [json-c/json-c#302]
`false`, `true`, `"hi"`, `12`, and `null` won't be parsed by json_tokener_parse_ex (unexpected end of data).

```
#include <stdio.h>
#include <string.h>

#include <json-c/json.h>
#include <json-c/json_tokener.h>

int main(void)
{
  const char *s = "12";
  struct json_tokener *tok = json_tokener_new();
  struct json_object *obj = json_tokener_parse_ex(tok, s, strlen(s));

  if (tok->err != json_tokener_success) {
      printf("%s\n", json_tokener_error_desc(tok->err));
  }
  json_tokener_free(tok);
  return 0;
}
```
EDIT: works with objects and arrays. the basic types appear to require zero-termination.

**Comment by yogo1212** [comment]
Also, https://github.com/json-c/json-c/blob/master/json_tokener.h#L149 is wrong:
```
#include <stdio.h>
#include <string.h>

#include <json-c/json.h>
#include <json-c/json_tokener.h>

int main(void)
{
  json_object *j = json_tokener_parse("null");
  printf("%p\n", j);
  return 0;
}
```

**Comment by yogo1212** [comment]
json_tokener_success for `12{` is a bit weird:
```
#include <stdio.h>
#include <string.h>

#include <json-c/json.h>
#include <json-c/json_tokener.h>

int main(void)
{
  const char *s = "12";

  json_tokener *tok = json_tokener_new();
  enum json_tokener_error jerr;
  json_object *j = json_tokener_parse_ex(tok, s, strlen(s));
  jerr = json_tokener_get_error(tok);
  if (jerr == json_tokener_continue) {
    json_tokener_parse_ex(tok, "{", 1);
  }
  jerr = json_tokener_get_error(tok);
  printf("jerr = %s\n", json_tokener_error_desc(jerr));
  printf("j = %p\n", j);
  return 0;
}
```

**Comment by yogo1212** [comment]
`"{ "` yields success as well?! how? why?
```
#include <stdio.h>
#include <string.h>

#include <json-c/json.h>

int main(void)
{
  const char *s = "{ ";

  struct json_object *j;
  enum json_tokener_error jerr;
  struct json_tokener *tok = json_tokener_new();

  j = json_tokener_parse_ex(tok, s, strlen(s) + 1);
  jerr = json_tokener_get_error(tok);
  printf("jerr = %s\n", json_tokener_error_desc(jerr));
  printf("j = %p\n", j);
  return 0;
}
```

**Comment by hawicz** [comment]
These must be zero terminated, or otherwise be followed by some byte that does not extend the token being parsed, so the parsing code can properly distinguish between there being only the valid token vs the bytes parsed so far being just the start of some other invalid token.
For instance, until it reaches a zero byte, json_tokener_parse_ex() has no way of knowing whether the four bytes 't', 'r', 'u', 'e' are the valid token "true" or just the start of something invalid like "truexyz".

For the "null" test case, the paragraph at line 149 that you referenced explains the proper way to check for errors (i.e. compare json_tokener_get_error(tok) against json_tokener_success).  Use json_tokener_parse_ex(), not json_tokener_parse(), if you care about distinguishing these cases.

For the "12{" test case, it correctly sets char_offset to 2 when I try running it.

For the "{ " test case, I get json_tokener_continue instead, which is to be expected.

Everything seems to be working as it should.
