### ISSUE TITLE
VERBOSE=1 make check; tests/test_util_file.test.c and tests/test_util_file.expected out of sync

### ISSUE THREAD

**Issue by JungHong** [json-c/json-c#313]
1.  on cygwin64 on windows 8.1, 
autoredonf --version --> 2.69
autoconf --version -----> 2.69
automake --version ---> 1.15
gcc --version           ---> 5.4.0
libtool --version       --->2.4.6

2. many changes to configure.ac and Makefile.am were required for autoreconf -vi and ./configure to complete without errors.  Do you want the changes that were needed for autoreconf -vi and ./configure to complete without errors?

And if so, how do you want the changes.

3. 'make check' reported fail in tests/test_util_file.c
'VERBOSE=1 make check'
shows that there are no errors in ./tests/testSubDir/test_util_file.test/test_util_file.out  It was just that the distributed file, /root/json-c/tests/test_util_file.expected  is out of sync.

The following solved this problem
 cp ./tests/testSubDir/test_util_file.test/test_util_file.out /root/json-c/tests/test_util_file.expected

4. Now 'make check' executes without errors.

JPH

**Comment by ploxiln** [comment]
Instead of `autoreconf -vi` you should run [autogen.sh](https://github.com/json-c/json-c/blob/master/autogen.sh) which contains the important argument `-Iautoconf-archive/m4`.

Copying the actual output to the reference expected output will of course make it match. But will it be _correct_ ... you'll have to look at the actual differences to figure out.

**Comment by hawicz** [comment]
If there are changes beyond simply specifying the -I option, please let us know what they are.

As for test_util_file, what are the differences?

**Comment by hawicz** [comment]
Can't do anything w/o details, closing.
