### ISSUE TITLE
Synchronize "potentially racy" random seed in lh_char_hash()

### ISSUE THREAD

**Issue by seltzy** [json-c/json-c#337]
There's currently no fallback for `__sync_val_compare_and_swap`/`InterlockedCompareExchange` in `lh_char_hash`. In some toolchains neither of these are available, which triggers a warning that must be explicitly disabled for compilation to succeed. What is the worst case scenario if a race occurs, and could this be avoided by adding a mutex of some sort in the worst case?

**Comment by hawicz** [comment]
The worst case is that two threads simultaneously cause the very first fields added to the very first json_type_object (not necessarily the same object), resulting in different random_seed values in each thread.  At some point after this, one of those random_seed values ends up propagating across to the other thread(s), and the losing thread has one (or more) fields stored in a slot that no longer matches what it would be when the hash is recalculated.
Once that happens, what happens when you try to access that field becomes hard to predict.  Either:
* All the slots between ${correct-hash-value} and ${lost-hash-value} are filled, and access to the field just becomes slow, or
* There is a gap, and it appears as if the field has disappeared.

As entries are added to the object, the hash-table eventually gets resized (after 16 fields are added), the hashes are recalculated, and the problem mostly "fixes" itself, except for a possible memory leak if a field was re-added with the same key and we hit the "gap" case.

The easiest fix?  This:
`random_seed = 1234;`
i.e. just punt on the randomness, at the expense of being _predictably_ vulnerable to poor performance up to DoS levels (i.e. CVE-2013-6371) when handling an object with fields that all hash to the same value.
It seems better to leave it as-is, and just say that if you're on running in an environment where that racy initialization is possible then you need to create at least one field in at least one object in a single-threaded way.

If we were to add a dependency on, say, pthreads, then it could _theoretically_ be protected with a mutex or the use of pthread_once, but at significant performance expense, since lh_char_hash is used all the time.

**Comment by hawicz** [comment]
Note that the warning is no longer there.  The initialization is still racy, but at least you'll be able to build the library without modifying the code.

**Comment by seltzy** [comment]
Wouldn't it be best to leave the warning and disable `-Werror`? How else will users know about the race condition?
