### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by xverizex** [json-c/json-c#423]
How to delete objects that were received by json_object_new_string? If you can not delete, will there be a memory leak or not?

**Comment by ploxiln** [comment]
`json_object_new_string()` returns a pointer to a new `struct json_object`. All json objects use reference-counting. If you call `json_object_put()` and it decrements the reference count of the object to zero, then the object will be freed. But usually you add this string object to another json object, and only call `put()` on the root object when you're done with the whole thing ...

http://json-c.github.io/json-c/json-c-0.13/doc/html/json__object_8h.html#a68c383f54544fca19b5f2425be397600

**Comment by r4ph0u** [comment]
Hello, just discovering this library.
so here it what I have to do when i no longer need the object :   ` json_object_put( main_json_object)`
Is it correct ?

**Comment by andrewhodel** [comment]
https://stackoverflow.com/questions/14879994/how-to-free-json-object/63289941#63289941

Some good info on this there.








You have to understand how the library works.

`json_tokener_parse()` is first, and it creates an object that will act as a memory managing parent that all objects which are created from it use to access the data they define.

So if you get all the way down to making a char *str for a string field, that field doesn't actually store the string, the original object returned from `json_tokener_parse()` does.

This is the reason that you can't just use a normal free() and expect things to work as if it was a char array or something.

To be safe, don't use the `json_tokener_parse_ex()` function because you will have to also free the object that is the tokener, with `json_tokener_parse()` you don't need that argument.

Beyond that, to safely close everything just do:

```
while (json_object_put(orig_object) != 1) {
  // keep freeing
}
```

You should only need to do that once, but the library may change.

**Comment by hawicz** [comment]
This has some terrible advice.

Avoiding json_tokener_parse_ex() because you don't want to free the tokener isn't "being safe", it's being lazy.  (which could be perfectly fine, if you don't need the fine grained control that having a tokener object gives you)

Calling json_object_put in a loop implies that your program has completely lost track of what it has allocated and incremented reference counts for, and is a great way to end up using already freed memory, including calling json_object_put() on an object that is no longer valid.

**Comment by andrewhodel** [comment]
The tokener object has no options.

You didn't see that the loop is based on the put() return value.

Quit fighting, that's how you free the objects this library creates.

**Comment by hawicz** [comment]
The tokener object _does_ have operations that can be performed on it to either control parsing or obtain the results of parsing.  Please see the functions at http://json-c.github.io/json-c/json-c-current-release/doc/html/json__tokener_8h.html for details.

Actually, I _did_ see that your loop checks the return value, and I still maintain that calling it in that way is a bad idea.  Though you might manage to cause the "orig_object" to be freed, calling json_object_put in a loop is dangerously sloppy and using such an approach in any non-trivial program will quite likely lead to use-after-free errors (and for simple programs it's entirely unnecessary to loop).

**Comment by andrewhodel** [comment]
I guess you just don’t know how the compiler works.


Andrew
