### ISSUE TITLE
CMakeLists.txt doesn't contain json_object_iterator.h which json.h includes

### ISSUE THREAD

**Issue by ttjsu-aws** [json-c/json-c#465]
https://github.com/json-c/json-c/blob/master/CMakeLists.txt#L200 missing from CMakeLists.txt in json-c-0.13.

**Comment by hawicz** [comment]
Actually, I think the relevant commit for the style of CMakeLists.txt that's on the 0.13 branch is 37a2edf, but that happened after the most recent 0.13 branch release.
Just because the build completes doesn't mean that everything that's installed is actually usable, and I verified that using cmake to build from the 0.13 branch *does* result in a broken install.
I copied the fix over as 0daf8dc, so if you really need to build off of that branch you can, but this doesn't warrant a new release.
