### ISSUE TITLE
Segmentation fault in json_object_iter_begin

### ISSUE THREAD

**Issue by amrithathorath** [json-c/json-c#472]
I see the following error:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000416502 in json_object_iter_begin (obj=0x6ba3f0) at /home/amritha/new_parser/code/commander/parsers/parse-json/json-c/json_object_iterator.c:74
74          iter.opaque_ = pTable->head;
```

My code is shown below:

```
struct json_object *in = NULL;
struct json_object_iterator it; 
struct json_object_iterator itEnd; 

json_read_data(filename, &in); // JSON object stored in json_object type

it = json_object_iter_begin(in); // point to first item
itEnd = json_object_iter_end(in); // point to last item

while (!json_object_iter_equal(&it, &itEnd)) {
       printf("%s\n", json_object_iter_peek_name(&it));
       json_object_iter_next(&it);
      }
```
My input (partial) file is:

> [ {
>   "acvVersion" : "0.5"
> }, {
>   "vsId" : 9168,
>   "algorithm" : "SHA-1",
>   "isSample" : false,
>   "testGroups" : [ {
>     "tgId" : 1,
>     "testType" : "AFT",
>     "inBit" : false,
>     "inEmpty" : true,
>     "tests" : [ {
>       "tcId" : 1,
>       "msg" : "A6",
>       "len" : 8
>     }, {
>       "tcId" : 2,
>       "msg" : "5699",
>       "len" : 16
>     }, {
>       "tcId" : 3,
>       "msg" : "43C60C",
>       "len" : 24
>     }, {
>       "tcId" : 4,
>       "msg" : "05B85906",
>       "len" : 32
>     }, {
>       "tcId" : 5,
>       "msg" : "D6AB8CB8B6",
>       "len" : 40
>     }

Can anyone please suggest how to fix this? TIA!

**Comment by hawicz** [comment]
json_object_iterator is for iterating through the fields in a object of type json_type_object, but (based on your input) you're passing a json_type_array to json_object_iter_begin().  If it's actually suppose to be an array, then you should just use a plain old for-loop, with json_object_array_length() and json_object_array_get_idx() to get each entry.
You should also check the type of the object returned from your json_read_data() function using json_object_get_type() to make sure it's what you expect, and so you can generate a useful error if it's not.

**Comment by amrithathorath** [comment]
Thanks for the input. I've got this code:

```
if(json_object_get_type(in) == json_type_array)
      printf("obj in is of type array\");

int ii;

 for(ii = 0; ii < json_object_array_length(ii); ii++)
{
     json_object *obj = json_object_array_get_idx(in, ii);
     printf("\t[%d]=%s\n", (int)ii, json_object_to_json_string(obj));
 }

```

When I run  the code, I get this output:

```
obj in is of type array
Commander: /home/amritha/new_parser/code/parsers/parse-json/json-c/json_object.c:1233: json_object_array_length: Assertion `json_object_get_type(jso) == json_type_array' failed.
Aborted (core dumped)
```
Clearly, my input object "in" is of array type. Still get an error accessing each index item. Any help is aprrepciated. TIA!!

**Comment by hawicz** [comment]
That's quite odd, and doesn't seem like it should be possible.  I'd say load up the core dump in gdb and see what type the object appears to be at the point that it crashed.

Also, what version/commit of json-c are you using?  There is no code at line 1233 of the current head of the master branch (ee4691c), and line 1233 on the json-c-0.13 branch is in a different function (_del_idx instead of _get_idx)

**Comment by ploxiln** [comment]
in `json_object_array_length(ii)`, `ii` should be `in`

**Comment by atlesn** [comment]
I just went in this trap myself while doing some initial try-outs of the library.

This mistake by incorrectly passing an array to `json_object_iter_begin` is very easy to make.

Imagine that an implementation works fine as long as it receives associative JSON data, but the author hasn't added in a check for which object types has been parsed. A remote could then trigger a crash by simply passing in an array in the JSON data.

I understand that you're supposed to check the object type before passing it to this function, but a better solution could have been that the `json_object_iter_begin` somehow could return an error instead of having the program segfault. It could also possibly check if `json_object_get_object` returned `NULL` and return and iterator pointing to `end` in this case?

**Comment by hawicz** [comment]
I think the current behavior is the best that can be managed within the constraints of the language (C) that this is written in.  Were we to return an error somehow, then you'd need to check for it, else risk undefined behavior or a crash later on accessing the invalid iterator.  Were we to return the end iterator, you'd end up with a program that doesn't crash, but mysteriously doesn't "work".
I think that failing early, through it may crash the program, is better.
That said, this could be improved by having an explicit check for the correct type in json_object_iter_begin, and emitting a more useful message before terminating.
