### ISSUE TITLE
json-c-0.12.1  failed making from source code

### ISSUE THREAD

**Issue by yh371174229** [json-c/json-c#480]
![image](https://user-images.githubusercontent.com/5948456/54520225-3178ad80-49a3-11e9-941a-753b6d278935.png)

**Comment by hawicz** [comment]
Well, your report is rather lacking in any details, but I'm going to assume you fetched the json-c-0.12.1.tar.gz, ran configure with some prefix, and then make.
I'm able to reproduce the problem, and it appears to be because aclocal.m4 ended up newer than config.h.in.
A workaround for that is to do "touch config.h.in" before running make.  (or install autoconf, like the message says)

**Comment by yh371174229** [comment]
I install the newest version and success
