### ISSUE TITLE
Turning off shared libs causes target duplication or build error

### ISSUE THREAD

**Issue by qyot27** [json-c/json-c#598]
I notice that the static/shared stuff was only committed yesterday, so this may be in the fix list already, but anyway:
```
cmake ../../ -DCMAKE_INSTALL_PREFIX="/usr/x86_64-w64-mingw32" \
-DCMAKE_TOOLCHAIN_FILE="/usr/x86_64-w64-mingw32/toolchain-x86_64-w64-mingw32.cmake" \
-DCMAKE_C_FLAGS="-march=core2" -DBUILD_SHARED_LIBS:bool=off

make -j$(nproc)
```

This causes the regular json-c library target to be static from the start, and then it proceeds to build it *again* using the json-c-static target.

I wouldn't necessarily have been aware of this, though, if it wasn't for the fact that I use Ninja rather than Make whenever I'm compiling a project that uses CMake.  With Ninja, this duplication causes an error:
```
[amd64:$] ninja
ninja: error: build.ninja:438: multiple rules generate libjson-c.a [-w dupbuild=err]
```

It would appear the fix is simply changing line 405 in CMakeLists.txt from `if (BUILD_STATIC_LIBS)` to `if (BUILD_STATIC_LIBS AND BUILD_SHARED_LIBS)`.

**Comment by hawicz** [comment]
hmm.. I'm not sure just that is actually the complete fix, since I would expect that on Windows the library name needs to change so it doesn't conflict with the "import library" created for the shared lib build.
I'm committing the change you suggested as a stop-gap; the problem with the Windows build is a separate issue though.  (originally PR#415, but broken again with the new cmake machinery)
