### ISSUE TITLE
Naming conflict when using both json-c and jansson

### ISSUE THREAD

**Issue by mdorier** [json-c/json-c#677]
I'm developing a project that has to link against 2 libraries. One library internally uses and links against json-c, the other internally uses and links against jansson. While json-c and jansson have a generally different API, there is one common function name between the two (that I'm aware of, at least): `json_object_get()`. As a result, I am getting runtime errors, apparently because one library is using the function from the other.

I'm not sure what is the right solution. I would suggest modifying the json-c API as follows:

- rename `json_object_get` into `json_object_incref`
- rename `json_object_put` into `json_object_decref` (for consistency)
- add `#define json_object_put json_object_decref` to avoid breaking user code
- add `#define json_object_get json_object_incref`

(this, however, breaks ABI compatibility, since `json_object_put` and `json_object_get` won't be in the ABI anymore).

I was going to submit a similar issue on the jansson repo to make them aware of the problem, but in my opinion it makes more sense to modify json-c: while `json_object_get` is consistent with the jansson API (in which it is used to get a field from an object), it really wasn't clear to me when using json-c, from their names, that `json_object_get` and `json_object_put` were used to increment/decrement reference counts.

**Comment by ploxiln** [comment]
symbol versioning was added to both jansson (in akheron/jansson#540) and json-c (in json-c/json-c#639) in order to work-around this problem

**Comment by hawicz** [comment]
We will not be renaming any of these function, they have been part of json-c since it was first created and cannot be changed without a (quite significant) major version bump.

Are you using the most recent release of json-c (0.15) and the most recent version of jansson (whatever that is)?   You'll need both libraries to be using symbol version in order for this to work reliably.

Your only other option is to *not* link against both the json-c-using and the jansson-using libraries, at least not within a single process.  If you _really_ need to use both you'd need to split into two cooperating programs and have them make calls across with some kind of local ipc.

**Comment by hawicz** [comment]
I don't think there's anything to do here, closing.
