### ISSUE TITLE
Optional parameter for packing as array

### ISSUE THREAD

**Issue by Disinterpreter** [json-c/json-c#693]
**Describe the bug**
There is a problem with `json_object_array_to_json_string`. Which always pack the data into arrays `[]`. I'd like to see it optional.

**Steps To Reproduce**
Convert any string as JSON.

**Version and Platform**
https://github.com/multitheftauto/mtasa-blue/tree/master/vendor/json-c

**Additional info**
https://github.com/multitheftauto/mtasa-blue/issues/1073

**Comment by hawicz** [comment]
Of course json_object_array_to_json_string packs the data into arrays, that's the whole purpose of that function.

Your steps to reproduce don't make any sense.  What kind of json_object are you attempting to serialize?  Can you please provide some sample code that shows the problem?

Note that the suggestion to "make a parameter which would be cut first and last brackets." is a terrible idea, since obviously you'd be papering over some underlying problem.

**Comment by Disinterpreter** [comment]
> 
> 
> Of course json_object_array_to_json_string packs the data into arrays, that's the whole purpose of that function.

Yeah, sorry, I didn't think about this.
