### ISSUE TITLE
How to build json-c-0.15 for arm arch

### ISSUE THREAD

**Issue by TommyChap** [json-c/json-c#707]
Hi

I want build json-c-0.15 for ARM Arch by my x86-64 Server.
I can't get "libjson-c.a" for arm, but build sucessful.

cmd is "cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc ../"

What should I do?

Thank you.

**Comment by hawicz** [comment]
You should provide some more detail.  i.e. what _do_ you get from the build, the .so files?  What are the most recent files in your build directory?  What's the output (at least the last few lines) from running make?

**Comment by TommyChap** [comment]
@hawicz 
My cmake cmd is "cmd is "cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc ../".
My make cmd is "make", and make output is not error or warning, such as
"[ 87%] Building C object tests/CMakeFiles/test_parse.dir/test_parse.c.o
[ 88%] Linking C executable test_parse
[ 88%] Built target test_parse
[ 90%] Building C object tests/CMakeFiles/test_json_pointer.dir/test_json_pointer.c.o
[ 91%] Linking C executable test_json_pointer
[ 91%] Built target test_json_pointer
[ 92%] Building C object tests/CMakeFiles/test_int_add.dir/test_int_add.c.o
[ 94%] Linking C executable test_int_add
[ 94%] Built target test_int_add
[ 95%] Building C object tests/CMakeFiles/test_locale.dir/test_locale.c.o
[ 97%] Linking C executable test_locale
[ 97%] Built target test_locale
[ 98%] Building C object apps/CMakeFiles/json_parse.dir/json_parse.c.o
[100%] Linking C executable json_parse
[100%] Built target json_parse"

I look out file arch like
"
> file libjson-c.so.5.1.0
libjson-c.so.5.1.0: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=1cdd82de7e1c4e6b309932fc513de11a6859ae28, with debug_info, not stripped
> file libjson-c.a
libjson-c.a: current ar archive
"

But i want to static library and arm arch.

Thank you.

**Comment by ploxiln** [comment]
The `file` command won't tell the ISA of the static archive, but it seems safe to assume it's ARM if the shared-object is ARM. I think it worked.

**Comment by TommyChap** [comment]
I "readelf libjson-c" can get this ARCH, like
```
File Attributes
  Tag_CPU_name: "5T"
  Tag_CPU_arch: v5T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_optimization_goals: Aggressive Debug
```
So, my problem is solved.

Thank you.

**Comment by nanfengnan1** [comment]
@haruzheng , i compile json-c and. use "cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc ../" and execute "make" command, but i only get libjson-c.a. in fact, i want to dynamica json-c library.

**Comment by haruzheng** [comment]
Hi @nanfengnan1 
Sorry, I forget to reply this. Haha.

You can remove  **-DBUILD_SHARED_LIBS=OFF**, because it is mean trun-off **dynamica json-c library**.
like "cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc ../;make".

```
/tmp/json-c/build (json-c-0.15)> ls
CMakeCache.txt              CMakeFiles/              CTestTestfile.cmake    Testing/       check-version-script.sym  doc/                 json_config.h  libjson-c.so.5@
CMakeDoxyfile.in            CPackConfig.cmake        DartConfiguration.tcl  apps/          cmake_install.cmake       json-c-config.cmake  libjson-c.a    libjson-c.so.5.1.0*
CMakeDoxygenDefaults.cmake  CPackSourceConfig.cmake  Makefile               apps_config.h  config.h                  json-c.pc            libjson-c.so@  tests/
```

Hope it can fixed your problem.
Haru

**Comment by nanfengnan1** [comment]
thanks for you, i try to make clean , make distclean and slove it.
&nbsp;


流年浅夏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [json-c/json-c] How to build json-c-0.15 for arm arch (#707)





 
Hi @nanfengnan1
 Sorry, I forget to reply this. Haha.
 
You can remove  -DBUILD_SHARED_LIBS=OFF, because it is mean trun-off dynamica json-c library.
 like "cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc ../;make".
 /tmp/json-c/build (json-c-0.15)&gt; ls CMakeCache.txt              CMakeFiles/              CTestTestfile.cmake    Testing/       check-version-script.sym  doc/                 json_config.h  libjson-c.so.5@ CMakeDoxyfile.in            CPackConfig.cmake        DartConfiguration.tcl  apps/          cmake_install.cmake       json-c-config.cmake  libjson-c.a    libjson-c.so.5.1.0* CMakeDoxygenDefaults.cmake  CPackSourceConfig.cmake  Makefile               apps_config.h  config.h                  json-c.pc            libjson-c.so@  tests/  
Hope it can fixed your problem.
 Haru
