### ISSUE TITLE
-static linker flag result in building failed

### ISSUE THREAD

**Issue by leleliu008** [json-c/json-c#787]
**Steps To Reproduce**
```
apk add cmake gcc make

git clone https://github.com/json-c/json-c
cd json-c

cmake -S . -B build.d -DCMAKE_EXE_LINKER_FLAGS=-static -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON
cmake --build build.d
```

**report following:**
```
[ 36%] Linking C executable test1Formatted
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `../libjson-c.so.5.2.0'
collect2: error: ld returned 1 exit status
gmake[2]: *** [tests/CMakeFiles/test1Formatted.dir/build.make:114: tests/test1Formatted] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1048: tests/CMakeFiles/test1Formatted.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
```

**cat /etc/os-release**
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.4
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by leleliu008** [comment]
my solution is:

```
sed -i 's|set(APPS_LINK_LIBS "${PROJECT_NAME}")|set(APPS_LINK_LIBS "${PROJECT_NAME}-static")|' apps/CMakeLists.txt
```

```
cmake -S . -B build.d -DCMAKE_EXE_LINKER_FLAGS=-static -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_TESTING=OFF
```

**Comment by hawicz** [comment]
If you're going to override the link flags in that way then yes, workarounds as you suggest are going to be required.  If you skip building the shared libraries (i.e. `-DBUILD_SHARED_LIBS=OFF`) then I expect it'll work without needing to tweak the CMakeLists.txt file.
On my system I also needed `-DDISABLE_EXTRA_LIBS=ON` because it seems that the static libbsd doesn't include arc4random, and cmake's `check_symbol_exists()` doesn't use `CMAKE_EXE_LINKER_FLAGS`.  The way that cmake checks for the presence of various features doesn't really allow for discrepancies like this, so if you want things to work reliably you'll just need to build json-c separately for shared and static libs.
