### ISSUE TITLE
I am looking whether this CVE - CVE-2021-32292 is impacted by json-c version v0.13.1or not ?

### ISSUE THREAD

**Issue by sem3t** [json-c/json-c#830]
Hi,

I am working on this CVE-2021-32292 vulnerability and its description says- 
An issue was discovered in json-c through 0.15-20200726. A stack-buffer-overflow exists in the function parseit located in json_parse.c. It allows an attacker to cause code Execution. 
and it says it is impacted up to 0.15-20200726
![image](https://github.com/json-c/json-c/assets/144909737/bd018965-6371-48aa-9cf4-ea0ae04de8aa)
But my doubt is this json_parse.c and parseit() it self not introduced in json-c 0.13.1 version so is it imapated with this vulnerability or not? please help me to understand that and clear my doubt.

Thanks,
Neha Gupta

**Comment by hawicz** [comment]
No, earlier versions of json-c are not affected by this.  Also, given that this is in the json_parse cli it doesn't affect anyone that's just using the library APIs, and some packaged versions of json-c might not even install that binary.

**Comment by hawicz** [comment]
To provide a bit more color here, the "vulnerable" code was introduced (on master) on 20200420, but since it's just in the `json_parse` binary, which is an auxiliary example program, the CVE score is _way_ too high.  I'd say that this hardly warrants a CVE at all, but since there is one I've asked for its description to be updated to better reflect what the bug actually was.

Nothing that uses the json-c API is affected by this.  The only way it might cause a problem is if someone were to build some service around executing the json_parse binary instead of using the normal API methods.
